Add AKS guide for testing Kubernetes support
iterative/terraform-provider-iterative pull request #259
Opened 2021-11-23 17:10 UTC by 0x2b3bfa0

# Closes #257[^1]

Not sure if [`subcategory`](https://www.terraform.io/docs/registry/providers/docs.html#example) works for guides. 🙈 

[^1]: Copied from https://www.notion.so/iterative/Setting-up-Azure-Kubernetes-Service-c20e523be5484ec29a2c2ad5fcc76be2

2021-11-23 17:11 UTC, 0x2b3bfa0 commented
Copied from [this Notion page](https://www.notion.so/iterative/Setting-up-Azure-Kubernetes-Service-c20e523be5484ec29a2c2ad5fcc76be2), may need extensive improvements.

2021-11-23 17:13 UTC, 0x2b3bfa0 commented
Maybe also worth mentioning that this repository has enough CI/CD magic to run tests on our infrastructure, upon approval?

2021-11-23 17:21 UTC, 0x2b3bfa0 commented
Other alternatives for testing:
* https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-eks-setup.html
* https://cloud.google.com/kubernetes-engine/docs/how-to/gpus
* https://minikube.sigs.k8s.io/docs/start

2021-11-23 17:34 UTC, 0x2b3bfa0 commented
Confirmed that `subcategory` works really well, although guides with a custom `subcategory` don't appear under <kbd>Guides</kbd> but rather under <kbd>{subcategory}</kbd> on the side bar.
![Captura de pantalla 2021-11-23 a las 18 33 39](https://user-images.githubusercontent.com/11387611/143075362-486a4745-0336-4292-aed0-0fb8a3434638.png)

2021-11-23 17:35 UTC, 0x2b3bfa0 commented
Maybe just <kbd>Development</kbd> would look better than <kbd>Development and Testing</kbd> 🤔

2021-11-23 17:36 UTC, 0x2b3bfa0 commented on docs/guides/testing-kubernetes.md
> +subcategory: Development and Testing
```suggestion
subcategory: Development
```

Much better, to my mind.

2022-01-24 08:45 UTC, casperdcl requested changes
srry for the review delay

2022-01-24 08:45 UTC, casperdcl commented on docs/guides/testing-kubernetes.md
> +
```suggestion
az extension add --name aks-preview

az provider register --namespace Microsoft.ContainerService
```

2022-01-24 08:45 UTC, casperdcl commented on docs/guides/testing-kubernetes.md
> +# Setting up Azure Kubernetes Service
```suggestion
page_title: Azure Kubernetes Service
subcategory: Development
---

# Azure Kubernetes Service
```

2022-01-24 08:45 UTC, casperdcl commented on docs/guides/testing-kubernetes.md
> +First of all, we need to install the `az` tool following the official documentation on the Microsoft documentation portal: [https://docs.microsoft.com/en-us/cli/azure/install-azure-cli](https://docs.
```suggestion
Install the `az` tool following the official documentation on the Microsoft documentation portal: [https://docs.microsoft.com/en-us/cli/azure/install-azure-cli](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
```

2022-01-24 08:45 UTC, casperdcl commented on docs/guides/testing-kubernetes.md
> +In order to automatically provision GPU nodes for our cluster, we'll also need to enable the following experimental features through the `aks-preview` extension:
```suggestion
In order to automatically provision GPU nodes for the cluster, enable the following experimental features through the `aks-preview` extension:
```

2022-01-24 08:45 UTC, casperdcl commented on docs/guides/testing-kubernetes.md
> +The following commands will create an AKS cluster with a single node, keeping everything into a a new resource group for easier deletion of the resources:
```suggestion
The following commands will create an AKS cluster with a single node, keeping everything in a new resource group for easier deletion when done:
```

2022-01-24 08:45 UTC, casperdcl commented on docs/guides/testing-kubernetes.md
> +Azure has some wrappers for Kubernetes authentication and will generate for us the required credentials. The following command will produce a full-fledged `kubeconfig` string that can be directly sto
```suggestion
Azure has some wrappers for Kubernetes authentication, and can generate the required credentials. The following command will produce a full-fledged `kubeconfig` string that can be directly stored in a `KUBERNETES_CONFIGURATION` CI/CD environment secret:
```

2022-01-24 08:45 UTC, casperdcl commented on docs/guides/testing-kubernetes.md
> +-> **Note:** If you skip the `--file` option, settings will be saved to your computer's `~/.kube/config` file, that will be automatically used by `kubectl` if you ever need to run any sanity check ma
```suggestion
-> **Note:** Omitting the `--file -` option causes settings to be stored in the local computer's `~/.kube/config` file (which is automatically used by `kubectl` should you ever need to run a manual sanity check on the cluster).
```

2022-01-24 08:45 UTC, casperdcl commented on docs/guides/testing-kubernetes.md
> +  --name testKubernetesResourceGroup
```suggestion
az group delete --name testKubernetesResourceGroup
```

2022-01-24 08:45 UTC, casperdcl commented on docs/guides/testing-kubernetes.md
> +Once you've finished testing you can run the following command to delete the entire resource group, which includes the cluster and all its nodes:
```suggestion
Once you've finished testing you can run the following command to delete the entire resource group (including the cluster and all its nodes):
```

2022-01-24 08:45 UTC, casperdcl commented on docs/guides/testing-kubernetes.md
> +~> **Warning:** Please delete the entire resource group as soon as you finish using the cluster. They are really pricey, and you may end spending a lot of money just on testing. 🔥💵
```suggestion
~> **Warning:** Try to delete the entire resource group as soon as you finish using the cluster to avoid unnecessary expenses. 🔥💵
```

2022-01-24 08:57 UTC, 0x2b3bfa0 commented
🙏🏼 Thank you!

Has the backslash removal been performed with an automated tool (e.g. prettier) or just a manual suggestion? In the latter case, I'd consider leaving them as they were before. ⚔️

2022-01-24 09:58 UTC, casperdcl commented on docs/guides/testing-kubernetes.md
> +az provider register --namespace Microsoft.ContainerService
```suggestion
az extension add --name aks-preview
az provider register --namespace Microsoft.ContainerService
```

2022-01-24 09:59 UTC, casperdcl commented
> backslash removal [...] consider leaving them as they were before

Didn't make sense to me to have short lines broken. Any reason you did this?

2022-01-24 11:04 UTC, 0x2b3bfa0 commented
> _Didn't make sense to me to have short lines broken. Any reason you did this?_

🤷🏼‍♂️ [Consistency](https://www.gutenberg.org/files/16643/16643-h/16643-h.htm#SELF-RELIANCE). Still, it's just a matter of taste; let's leave it with your suggestion.

2022-01-26 12:47 UTC, casperdcl commented
> Ne te quaesiveris extra

:)

2022-01-26 12:47 UTC, merged