Add resource tagging support
iterative/terraform-provider-iterative pull request #599
Opened 2022-06-02 13:54 UTC by 0x2b3bfa0

Closes #598

2022-06-02 14:17 UTC, casperdcl requested changes
lgtm

2022-06-02 14:17 UTC, casperdcl commented on docs/resources/task.md
>  - `timeout` - (Optional) Maximum number of seconds to run before instances are force-terminated. The countdown is reset each time TPI auto-respawns a spot instance.
lower priority IMO :nail_care: :)

```suggestion
- `timeout` - (Optional) Maximum number of seconds to run before instances are force-terminated. The countdown is reset each time TPI auto-respawns a spot instance.
- `tags` - (Optional) Map of tags for the created cloud resources.
```

2022-06-02 14:35 UTC, dacbd commented
I go to bed and he beats me to it 😆

2022-06-02 14:37 UTC, 0x2b3bfa0 commented
> _he beats me to it_

Sleeping, or opening pull requests? 🦦

2022-06-02 14:48 UTC, casperdcl approved these changes

2022-06-02 14:57 UTC, dacbd commented
I might be being extra picky but for AWS as the example, the auto-scaling group doesn't get the tag, and more importantly, s3 objects are missing them as well.

2022-06-02 18:55 UTC, merged

2022-06-03 02:37 UTC, 0x2b3bfa0 commented
You're picky and it's awesome! 🙏🏼 Tracking this on https://github.com/iterative/terraform-provider-iterative/issues/601