Parse nested maps from viper configuration
iterative/terraform-provider-iterative pull request #639
Opened 2022-08-05 09:51 UTC by 0x2b3bfa0

Closes #638; convoluted workaround to keep `cobra` instead of `viper` as the primary schema.

2022-08-05 18:00 UTC, dacbd commented
Can you help my brain and give an example of what was broken and now fixed by this? I don't quite follow the info in the linked issue? 

this is broken?
```hcl
environment = { THINIG1 = "", THING2 = "" }
```
but this isn't?
```hcl
environment = { THINIG1 = "" }
```

2022-08-05 20:28 UTC, 0x2b3bfa0 commented
Both were broken. The standalone command-line tool ignored all the map-like attributes from a `main.tf` file.

2022-08-08 16:18 UTC, dacbd requested changes
It is improperly assigning values.

with:
```hcl
terraform {
  required_providers {
    iterative = { source = "github.com/iterative/iterative" }
  }
}
provider "iterative" {}
resource "iterative_task" "test" {
  cloud = "aws"
  machine = "t3.small"
  disk_size =-1
  storage {
    workdir = ""
    output = ""
  }
  environment = { 
    GITHUB_PAT= "",
    THING1 = "one", 
    THING2 = "two", 
    THING_ONE = "three",
    THING_TWO = "four"
  }
  script = <<-END
    #!/bin/bash
    env
  END
}
```

running the cli results with:
```
THING_TWO=two
GITHUB_PAT=*** #correctly set
THING_ONE=two
THING1=two
THING2=two
```

2022-08-08 16:34 UTC, 0x2b3bfa0 commented on cmd/create/create.go
>  			variables[name] = &value
```suggestion
		if copy := value; value != "" {
			variables[name] = &copy
```

The issue you describe wasn't introduce by this pull request, but... 🤦🏼‍♂️

2022-08-08 16:47 UTC, dacbd approved these changes

2022-08-08 21:17 UTC, merged