Mark sensitive environment variables for runners
iterative/terraform-provider-iterative pull request #665
Opened 2022-09-12 22:18 UTC by 0x2b3bfa0

2022-09-12 23:22 UTC, dacbd commented
⚠️ should require communication and migration instructions before being released ⚠️

2022-09-21 19:12 UTC, dacbd requested changes
will require changes with: https://github.com/iterative/cml/pull/1164#pullrequestreview-1108018382

2022-10-10 03:50 UTC, 0x2b3bfa0 commented on iterative/resource_runner.go
> +export CML_RUNNER_SENSITIVE_ENV=AWS_SECRET_ACCESS_KEY:AWS_ACCESS_KEY_ID:AWS_SESSION_TOKEN
```suggestion
export _CML_RUNNER_SENSITIVE_ENV=AWS_SECRET_ACCESS_KEY:AWS_ACCESS_KEY_ID:AWS_SESSION_TOKEN
```

2022-10-10 03:50 UTC, 0x2b3bfa0 commented on iterative/resource_runner.go
> +export CML_RUNNER_SENSITIVE_ENV=AZURE_CLIENT_ID:AZURE_CLIENT_SECRET:AZURE_SUBSCRIPTION_ID:AZURE_TENANT_ID
```suggestion
export _CML_RUNNER_SENSITIVE_ENV=AZURE_CLIENT_ID:AZURE_CLIENT_SECRET:AZURE_SUBSCRIPTION_ID:AZURE_TENANT_ID
```

2022-10-10 03:50 UTC, 0x2b3bfa0 commented on iterative/resource_runner.go
> +export CML_RUNNER_SENSITIVE_ENV=GOOGLE_APPLICATION_CREDENTIALS_DATA:CML_GCP_ACCESS_TOKEN
```suggestion
export _CML_RUNNER_SENSITIVE_ENV=GOOGLE_APPLICATION_CREDENTIALS_DATA:CML_GCP_ACCESS_TOKEN
```

2022-10-10 03:50 UTC, 0x2b3bfa0 commented on iterative/resource_runner.go
> +export CML_RUNNER_SENSITIVE_ENV=KUBERNETES_CONFIGURATION
```suggestion
export _CML_RUNNER_SENSITIVE_ENV=KUBERNETES_CONFIGURATION
```

2022-10-10 03:50 UTC, 0x2b3bfa0 commented on iterative/testdata/script_template_cloud_aws.golden
> +export CML_RUNNER_SENSITIVE_ENV=AWS_SECRET_ACCESS_KEY:AWS_ACCESS_KEY_ID:AWS_SESSION_TOKEN
```suggestion
export _CML_RUNNER_SENSITIVE_ENV=AWS_SECRET_ACCESS_KEY:AWS_ACCESS_KEY_ID:AWS_SESSION_TOKEN
```

2022-10-10 03:50 UTC, 0x2b3bfa0 commented on iterative/testdata/script_template_cloud_azure.golden
> +export CML_RUNNER_SENSITIVE_ENV=AZURE_CLIENT_ID:AZURE_CLIENT_SECRET:AZURE_SUBSCRIPTION_ID:AZURE_TENANT_ID
```suggestion
export _CML_RUNNER_SENSITIVE_ENV=AZURE_CLIENT_ID:AZURE_CLIENT_SECRET:AZURE_SUBSCRIPTION_ID:AZURE_TENANT_ID
```

2022-10-10 03:50 UTC, 0x2b3bfa0 commented on iterative/testdata/script_template_cloud_gcp.golden
> +export CML_RUNNER_SENSITIVE_ENV=GOOGLE_APPLICATION_CREDENTIALS_DATA:CML_GCP_ACCESS_TOKEN
```suggestion
export _CML_RUNNER_SENSITIVE_ENV=GOOGLE_APPLICATION_CREDENTIALS_DATA:CML_GCP_ACCESS_TOKEN
```

2022-10-10 03:50 UTC, 0x2b3bfa0 commented on iterative/testdata/script_template_cloud_kubernetes.golden
> +export CML_RUNNER_SENSITIVE_ENV=KUBERNETES_CONFIGURATION
```suggestion
export _CML_RUNNER_SENSITIVE_ENV=KUBERNETES_CONFIGURATION
```

2023-01-31 20:56 UTC, casperdcl commented
Is this blocked by https://github.com/iterative/cml/pull/802?

2025-12-22 15:11 UTC, 0x2b3bfa0 commented
Stale

2025-12-22 15:11 UTC, closed without merging